version: '3.8'

services:
  db:
    image: postgres:15.3-alpine
    container_name: car-detection-fyp-db
    restart: always
    environment:
      - POSTGRES_DB=fyp-db-nestjs
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root123
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  api:
    build:
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
    container_name: 'car-detection-fyp-api'
    network_mode: "host"
volumes:
  db:
    driver: local

